export const BRANDING = {
  governingBody: "BỘ CÔNG THƯƠNG",
  organizationName: "TRƯỜNG CAO ĐẲNG CÔNG THƯƠNG MIỀN TRUNG",
  organizationNameShort: "Trường Cao đẳng Công Thương miền Trung",
  shortName: "MITC",
  appName: "CỔNG ĐÁNH GIÁ SẢN PHẨM AI MITC",
  appNameShort: "Cổng Đánh giá Sản phẩm AI MITC",
  logoPath: "/logo.png",
  subtitle: "Trợ lý hỗ trợ Hội đồng đánh giá bản thuyết minh sản phẩm dự thi Hội thi Ứng dụng trí tuệ nhân tạo trong giảng dạy và quản lý",
  heroTitle: "TRỢ LÝ HỘI ĐỒNG ĐÁNH GIÁ SẢN PHẨM AI MITC",
  heroDescription: "Công cụ AI hỗ trợ đọc bản thuyết minh đánh giá sản phẩm AI và gợi ý điểm số cho Hội đồng chấm.",
  disclaimer: "Kết quả do AI đề xuất chỉ có giá trị tham khảo. Quyết định cuối cùng thuộc Ban Giám khảo/Hội đồng đánh giá MITC.",
  footerCopyright: `© ${new Date().getFullYear()} Trường Cao đẳng Công Thương miền Trung`,
  footerNote: "Phát triển bởi TS. Nguyễn Trung Hòa - Hotline/Zalo: 0888186788",
  securityWarning: "Lưu ý: Không tải lên dữ liệu mật, dữ liệu cá nhân nhạy cảm hoặc tài liệu nội bộ chưa được phép sử dụng. Hệ thống chỉ phân tích nội dung bản thuyết minh phục vụ Hội thi AI MITC. Kết quả AI chỉ mang tính hỗ trợ tham khảo.",
  resultDisclaimer: "Kết quả đánh giá do AI đề xuất dựa trên nội dung file báo cáo được cung cấp. Điểm số và nhận xét chỉ có giá trị tham khảo. Quyết định cuối cùng thuộc Ban Giám khảo/Hội đồng đánh giá MITC.",
  compareDisclaimer: "Kết quả so sánh chỉ hỗ trợ Hội đồng tham khảo, không thay thế quy trình chấm điểm và quyết định chính thức.",
  reportFooter: "Báo cáo do AI hỗ trợ tạo tự động, chỉ phục vụ tham khảo cho thành viên Hội đồng đánh giá. Quyết định cuối cùng thuộc Ban Giám khảo/Hội đồng đánh giá MITC.",
} as const;
